### ISSUE TITLE
Finalization TODOs

### ISSUE THREAD

**Issue by defeo** [Hugounenq-Cyril/Two_curves_on_a_volcano#1]
A checklist of things that need to be done before submission
- [x] Finalize abstract
- [x] Fix all todos inside text
- [x] Prop. 2.8, define F_n inside proposition
- [x] Review Section 3 (Luca)
- [x] Write Section 6 (Cyril)
- [x] Check bibliography entries
- [x] Do something with Appendix A (expand? merge into text?)
- [ ] Remove stray commented lines in source code.
- [x] ~~Mention Ionica-Joux at the beginning of Sec. 3~~
- [x] Clarify j vs E
- [x] Clarify kernel vs rational fraction
- [ ] log(q) or log q?
- [ ] O(r · M(r) · log 2 (r) + r · log(r) · log(q)), ou O(r M(r) log 2 (r) + r log(r) log(q)) ?

**Comment by Hugounenq-Cyril** [comment]
je pense qu'il faut parler de rational fraction plutôt que de kernel, car on parle de reconstruction rationnelle dans la suite, Couveignes parle lui aussi de fraction rationnelle

**Comment by Hugounenq-Cyril** [comment]
pour j vs E, pour simplifier les choses il serait peut être plus simple de ne considérer que E et pas j afin de ne pas avoir à écarter les twists qui feraient apparaitre des faux couples
pour la proposition 2.8, il ya juste le (iv) a changer en remplaçant n par n+1, sinon ça m'a l'air compatible avec la notation de la section 1

**Comment by Hugounenq-Cyril** [comment]
l'appendice A est en fait incluse peu ou prou dans la preuve de l'algorithme 1 , proposition 3.1

du coup la figure, ne sert pas trop, on pourrait la mettre en illustration de la 2.6 si on veut la garder

**Comment by defeo** [comment]
> pour j vs E, pour simplifier les choses il serait peut être plus simple de ne considérer que E et pas j afin de ne pas avoir à écarter les twists qui feraient apparaitre des faux couples

FTR, les twists ne font pas apparaître de faux couple : ils sont géométriquement isomorphes, et les isogénies sont des objets géométriques. Si φ:E→E' est rationnelle, elle l'est aussi pour les tordues de E et E'.

**Comment by Hugounenq-Cyril** [comment]
je vote pour les parenthèses autour du log et je préfère l'écriture sans point pour la multiplication

**Comment by defeo** [comment]
Remaining todos have been moved to #9
