### ISSUE TITLE
Major issue: make explicit the assumption k > h

### ISSUE THREAD

**Issue by defeo** [Hugounenq-Cyril/Two_curves_on_a_volcano#5]
p. 6 Prop 2.5: As stated this proposition places no constraints on k, but in what
follows (e.g. p. 8 line 3) the authors are often assuming that k ≥ h. When k < h we
have ℓ^h P = 0 and the Proposition is trivial (and this is also true if P has order less
than ℓ^h). Not making this assumption explicit made the paper very confusing to read,
as in several places they write expressions that may well be non-integral without this
assumption in contexts where an integer is required (for example, ℤ_ℓ does not contain
ℓ^(k-h) for k < h). In particular, as noted below, it is not obvious to me why, for example,
line 9 of Algorithm 1 and line 7 of Algorithm 2 are well defined.
On a related topic, I think there is an error in the proof of Proposition 2.5. The authors
write the matrix of π | T_ℓ (E 0 ) ∈ GL₂ (ℤ_ℓ) as

```
  / λ    ℓ^(h-k) x(λ-μ) \
  \ 0           μ       /
```

where h = v_ℓ (λ - μ), and x is an integer. The entry in the upper right has ℓ-adic
valuation v_ℓ (ℓ^(h-k) x(λ − μ)) = h - k + v_ℓ(x) + h, which will be negative if we choose k
large and take P = R so that x = 1. I think they want to replace k - h with h - k in
both the matrix and the condition on v_ℓ(x) ≥ k - h given later in the proof.

**Comment by plut** [comment]
- Alg. 1: fixed by commit `1c9eac7` ($$h$$ is mutable in the algorithm).
- Alg. 2: fixed by same commit (added missing hypothesis $$h \geqslant k+1$$).
- Proof of 2.5: fixed by commit `772ea7b` (the hypotheses of the proof did not ensure that $$\varphi$$ was rational; note: the reviewer-suggested fix was wrong).
- Also fixed an error that went un-noticed in the statement of 2.5, in commit `8ef4429`.

**Comment by defeo** [comment]
Why aren't we making the explicit assumption k>h in Algorithm 1 as requested by the reviewer? Is it because the height h is not known in advance? 

If so, this would slightly contradict the intro to Sec. 3, which assumes we have already constructed the Kummer tower up to the right level. Maybe we should clarify this.

**Comment by defeo** [comment]
Also, the fix introduced this typo in the statement of Prop. 2.5:

> ℓ^h P is an eigenvector of E → ℓ^h is an eigenvector of π

**Comment by plut** [comment]
@defeo Line 10 of Algorithm 1 computes h (or at least, h' = min (k, h), as stated in the algorithm output)

**Comment by defeo** [comment]
Isn't "previous discussion" better than "preceding discussion"? (frankly, I don't really know)

**Comment by defeo** [comment]
More typos:

> We note here that the matrices → We note here that the matrix

**Comment by defeo** [comment]
And yet one more typo introduced in the proof of Prop. 2.7 (I think this is the last one):

> we just note that since there exists a unique subgroup of order ℓ which either ascending or horizontal with a given direction

Maybe add "is" after "which"?
