### ISSUE TITLE
Minor details in prop 2.3

### ISSUE THREAD

**Issue by defeo** [Hugounenq-Cyril/Two_curves_on_a_volcano#8]
In the proof of proposition 2.3 it is said

> Conjugating the matrix [[λ,0], [μ, a]] by [[1,0], [1,b]] replaces a by a + b(λ - μ), and
> conjugating by [[0,c], [0,1]] replaces a by c·a, so that the valuation of a is well-defined.

However, calling A, B and C the three matrices appearing in the sentence above, the first conjugation is B^-1 A B, while the second is C A C^-1. That's very minor, but it'd be better to be consistent here. Of all the possible fixes, I suggest replacing a + b(λ - μ) by a - b(λ - μ).

Besides, I do not understand (anymore?) the sentence "so that the valuation of a is well-defined". How is a valuation not well-defined?

**Comment by plut** [comment]
“invariant under matrix conjugation”, et j'ai corrigé le signe
